name: Generate Content

on:
  schedule:
    - cron: "0 */6 * * *"   # CRON: co 6 godzin, dokładnie o 0:00, 6:00, 12:00, 18:00
  workflow_dispatch:        # pozwala też odpalić ręcznie w GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install node-fetch marked

      - name: Run generator
        run: node generator/generate.js
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Convert Markdown to HTML
        run: node generator/md2html.js

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new generated content" || echo "No new content"
          git push
