name: Generate Content

on:
  schedule:
    - cron: "0 */6 * * *"   # ⏰ co 6 godzin
  workflow_dispatch:        # ▶️ ręczne uruchomienie

jobs:
  build:
    runs-on: ubuntu-latest
    
        
    steps:
      
        
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # ważne, żeby dało się pushować
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run generator (create Markdown)
        run: node generator/generate.js
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Convert Markdown to HTML
        run: node generator/md2html.js

      - name: Generate PDF bundle
        run: node makepdf.js

      - name: Commit generated content
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"   
          git add content/ public/ state.json || echo "No directories to add"
          git commit -m "Add new generated content [skip ci]" || echo "No changes to commit"
          git push origin main
